source 'https://rubygems.org'

ruby '3.2.2'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '>= 5.0'
gem 'jbuilder'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'rack-cors'
gem 'jwt'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
end
